# Generated by Django 3.1.3 on 2020-12-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationmoes',
            name='batchid',
            field=models.IntegerField(default=0),
        ),
    ]
